# # Sample configuration file for Sidekiq.
# # Options here can still be overridden by cmd line args.
# #   sidekiq -C config.yml
# ---
:verbose: true
# :pidfile: ./tmp/pids/sidekiq.pid
# :namespace: sidekiq_namespace
:concurrency:  5
# :queues:
#   - [often, 7]
#   - [default, 5]
#   - [seldom, 3]